  function [] = plotColorMap(err_est_all_VI, err_est_all_FD,dt,end_time)
        figure()
        plot(2*dt:dt:end_time-2*dt,err_est_all_VI(1,2:end)','LineWidth',2)
        hold on
        plot(2*dt:dt:end_time-dt,err_est_all_FD(1,2:end)','LineWidth',2)
        set(gca, 'YScale', 'log')
        set(gca, 'FontSize',18)
        axis([ 0 30 10^-6 10^0])
        set(gca,'TickLabelInterpreter','LaTex')
        title({'Inertia'},'Interpreter','LaTex')
        legend({'Variational','Finite Difference'},'Interpreter','LaTex')
        xlabel('Time (sec.)','Interpreter','LaTex')
        ylabel('Frobenius norm error','Interpreter','LaTex')
        figure()
        plot(2*dt:dt:end_time-2*dt,err_est_all_VI(2,2:end)','LineWidth',2)
        hold on
        plot(2*dt:dt:end_time-1*dt,err_est_all_FD(2,2:end)','LineWidth',2)
        set(gca, 'YScale', 'log')
        set(gca, 'FontSize',18)
        axis([ 0 30 10^-6 10^0])
        set(gca,'TickLabelInterpreter','LaTex')
        title({'CoM'},'Interpreter','LaTex')
        legend({'Variational','Finite Difference'},'Interpreter','LaTex')
        xlabel('Time (sec.)','Interpreter','LaTex')
        ylabel('Norm error','Interpreter','LaTex')
        figure()
        plot(2*dt:dt:end_time-2*dt,err_est_all_VI(3,2:end)','LineWidth',2)
        hold on
        plot(2*dt:dt:end_time-1*dt,err_est_all_FD(3,2:end)','LineWidth',2)
        set(gca, 'YScale', 'log')
        set(gca, 'FontSize',18)
        axis([ 0 30 10^-6 10^0])
        set(gca,'TickLabelInterpreter','LaTex')
        title({'Mass'},'Interpreter','LaTex')
        legend({'Variational','Finite Difference'},'Interpreter','LaTex')
        xlabel('Time (sec.)','Interpreter','LaTex')
        ylabel('L1 norm error','Interpreter','LaTex')
        end
            